version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=kaja
      - MYSQL_DATABASE=notes_db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "6868:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        spring.datasource.url=jdbc:mysql://localhost:3306/notes_db?createDatabaseIfNotExist=true
        spring.datasource.username=root
        spring.datasource.password=kaja
        spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
        spring.jpa.generate-ddl=true
        spring.jpa.hibernate.ddl-auto=update
        spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: